trigger:
- development
stages:
- stage: A
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - powershell: |
        Write-Host "Current directory file list pre build"
        dir
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
    - powershell: |
        Write-Host "Current directory file list post build"
        dir
        Write-Host "Build Artifacts staging directory"
        Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'QMWebResources' #should be named after web resource prefix 
        publishLocation: 'pipeline'
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'QMWebResources'
    #     publishLocation: 'Container'
  # - deployment: Deploy
  #   condition: succeeded()
  #   dependsOn: Build
  #   pool:
  #     vmImage: 'vs2017-win2016'
  #   environment: DEV
  #   strategy:
  #     runOnce:
  #       deploy:
  - job: Deploy
    condition: succeeded()
    continueOnError: true
    dependsOn: Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Agent.BuildDirectory"
          Write-Host "Pipeline.Workspace"
          Get-ChildItem -Path "$(Agent.BuildDirectory)"
          Get-ChildItem -Path "$(Pipeline.Workspace)"
        errorActionPreference: 'continue'
    - task: MSCRMToolInstaller@12
      inputs:
        nugetFeed: 'official'
        psFeed: 'official'
    - task: MSCRMGetLatestPatch@12
      name: GetLatestPatchTask
      continueOnError: true
      inputs:
        crmConnectionString: '$(ConnectionDev)'
        solutionName: '$(CoreSolutionName)'
        existsVariableName: 'PatchExists'
        patchVariableName: 'LatestPatchName'
    - powershell: |
        Write-Host "##vso[task.setvariable variable=task.GetLatestPatchTask.PatchExists]$(PatchExists)"
        Write-Host "##vso[task.setvariable variable=task.GetLatestPatchTask.LatestPatchName]$(LatestPatchName)"
        Write-Host "Patch Exists =  $(PatchExists)"
        Write-Host "Latest Patch Name =  $(LatestPatchName)"
    - task: MSCRMExportSolution@12
      inputs:
        crmConnectionString: '$(ConnectionDev)'
        solutionName: '$(LatestPatchName)'
        exportManaged: false
        exportUnmanaged: true
        outputPath: '$(Pipeline.Workspace)'
    - task: MSCRMExtractSolution@12
      inputs:
        unpackedFilesFolder: '$(Pipeline.Workspace)'
        solutionFile: '$(Pipeline.Workspace)\$(LatestPatchName).zip'
    - powershell: |
        Get-ChildItem -Path "$(Pipeline.Workspace)"
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'QMWebResources'
        targetPath: '$(Pipeline.Workspace)'
    - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Pipeline.SourcesDirectory"
          Write-Host "Pipeline.Workspace"
          Get-ChildItem -Path "$(Pipeline.SourcesDirectory)"
          Get-ChildItem -Path "$(Pipeline.Workspace)"
        errorActionPreference: 'continue'
    - task: CopyFiles@2
      inputs:
        Contents: '$(Pipeline.Workspace)' 
        TargetFolder: '$(Pipeline.SourcesDirectory)\WebResources'
    - task: MSCRMPackSolution@12
      inputs:
        unpackedFilesFolder: '$(Pipeline.Workspace)'
        outputPath: '$(Pipeline.Workspace)'
        localize: false
    - powershell: 
        Get-ChildItem -Path "$(Pipeline.Workspace)"
        Get-ChildItem -Path "$(Pipeline.Workspace)"    

    - task: MSCRMImportSolution@12
      inputs:
        crmConnectionString: '$(ConnectionDev)'
        solutionFile: '$(Pipeline.Workspace)\$(LatestPatchName).zip'
        publishWorkflows: true
        holdingSolution: false
    #     override: true
    # - task: MSCRMApplySolution@12
    #   inputs:
    #     crmConnectionString: '$(ConnectionDev)'
    #     solutionName: '$(LatestPatchName)'
    #     useAsyncMode: true